trigger-workflow-allow-list:
  # - pulumi-alicloud <-- Not forked, but virtually always has new resources, and thus cannot really be automated.
  - pulumi-artifactory
  - pulumi-auth0
  - pulumi-azuread
  - pulumi-cloudamqp
  - pulumi-cloudflare
  - pulumi-cloudinit
  - pulumi-confluent
  - pulumi-consul
  - pulumi-docker
  - pulumi-ec
  - pulumi-equinix-metal
  - pulumi-gitlab
  - pulumi-hcloud
  - pulumi-kafka
  - pulumi-kong
  - pulumi-libvirt
  - pulumi-mongodbatlas
  - pulumi-ns1
  - pulumi-okta
  - pulumi-openstack
  - pulumi-opsgenie
  - pulumi-rabbitmq
  - pulumi-snowflake
  - pulumi-splunk
  - pulumi-tailscale
  - pulumi-terraform
  - pulumi-tls
  - pulumi-wavefront
