name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Pulumi preview
        uses: pulumi/actions@v3
        with:
          work-dir: pulumi
          command: preview
          stack-name: pulumi/github-issue-automation
