name: CI

on:
  pull_request:
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets. }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Preview
        run: cd pulumi && pulumi preview