name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Build Binary
        run: make .build/new-release-handler
      - name: Pulumi preview
        uses: pulumi/actions@v3
        with:
          work-dir: pulumi
          command: up -y
          stack-name: pulumi/github-issue-automation
