name: Release
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: make test
      - name: Pulumi preview
        uses: pulumi/actions@v3
        with:
          command: up -y
          stack-name: pulumi/github-issue-automation
